spring:  
  datasource:
    url: jdbc:postgresql://localhost:5430/recipe_dev
    username: recipe_dev_user
    password: dev_password
  sql:    init:      platform: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: recipe_database_create.sql